version: '3'
services:
  app:
    container_name: ma_blog
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 --pid tmp/pids/server.pid"
    build: .
    env_file: .env
    volumes:
      - .:/app:rw
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: ma_blog_db
    image: postgres:13.1-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
    driver: local
